logging:
  level:
    org.springframework.ai: DEBUG
spring:
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key:
      chat:
        base-url: https://openrouter.ai/api
        options:
          model: openai/gpt-4o-mini
      base-url: http://localhost:11434/
      embedding:
        options:
          model: nomic-embed-text-v2-moe:latest
          dimensions: 768

  application:
    name: SPRING-RAG-AI
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_demo
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
